STOP_WORDS = [
        "a", "about", "above", "across", "after", "afterwards", "again", "against",
        "all", "almost", "alone", "along", "already", "also", "although", "always",
        "am", "among", "amongst", "amoungst", "amount", "an", "and", "another",
        "any", "anyhow", "anyone", "anything", "anyway", "anywhere", "are",
        "around", "as", "at", "back", "be", "became", "because", "become",
        "becomes", "becoming", "been", "before", "beforehand", "behind", "being",
        "below", "beside", "besides", "between", "beyond", "bill", "both",
        "bottom", "but", "by", "call", "can", "cannot", "cant", "co", "con",
        "could", "couldnt", "cry", "de", "describe", "detail", "do", "done",
        "down", "due", "during", "each", "eg", "eight", "either", "eleven", "else",
        "elsewhere", "empty", "enough", "etc", "even", "ever", "every", "everyone",
        "everything", "everywhere", "except", "few", "fifteen", "fify", "fill",
        "find", "fire", "first", "five", "for", "former", "formerly", "forty",
        "found", "four", "from", "front", "full", "further", "get", "give", "go",
        "had", "has", "hasnt", "have", "he", "hence", "her", "here", "hereafter",
        "hereby", "herein", "hereupon", "hers", "herself", "him", "himself", "his",
        "how", "however", "hundred", "i", "ie", "if", "in", "inc", "indeed",
        "interest", "into", "is", "it", "its", "itself", "keep", "last", "latter",
        "latterly", "least", "less", "ltd", "made", "many", "may", "me",
        "meanwhile", "might", "mill", "mine", "more", "moreover", "most", "mostly",
        "move", "much", "must", "my", "myself", "name", "namely", "neither",
        "never", "nevertheless", "next", "nine", "no", "nobody", "none", "noone",
        "nor", "not", "nothing", "now", "nowhere", "of", "off", "often", "on",
        "once", "one", "only", "onto", "or", "other", "others", "otherwise", "our",
        "ours", "ourselves", "out", "over", "own", "part", "per", "perhaps",
        "please", "put", "rather", "re", "same", "see", "seem", "seemed",
        "seeming", "seems", "serious", "several", "she", "should", "show", "side",
        "since", "sincere", "six", "sixty", "so", "some", "somehow", "someone",
        "something", "sometime", "sometimes", "somewhere", "still", "such",
        "system", "take", "ten", "than", "that", "the", "their", "them",
        "themselves", "then", "thence", "there", "thereafter", "thereby",
        "therefore", "therein", "thereupon", "these", "they", "thick", "thin",
        "third", "this", "those", "though", "three", "through", "throughout",
        "thru", "thus", "to", "together", "too", "top", "toward", "towards",
        "twelve", "twenty", "two", "un", "under", "until", "up", "upon", "us",
        "very", "via", "was", "we", "well", "were", "what", "whatever", "when",
        "whence", "whenever", "where", "whereafter", "whereas", "whereby",
        "wherein", "whereupon", "wherever", "whether", "which", "while", "whither",
        "who", "whoever", "whole", "whom", "whose", "why", "will", "with",
        "within", "without", "would", "yet", "you", "your", "yours", "yourself",
        "yourselves"]


STOP_WORDS_TUPLES = [('down', 10),
        ('them', 11),
        ('but', 12),
        ('who', 12),
        ('it', 13),
        ('hundred', 13),
        ('already', 13),
        ('through', 14),
        ('show', 14),
        ('has', 14),
        ('now', 14),
        ('well', 14),
        ('the', 14),
        ('fify', 14),
        ('fire', 14),
        ('third', 14),
        ('all', 15),
        ('if', 15),
        ('where', 15),
        ('even', 15),
        ('both', 15),
        ('against', 15),
        ('seeming', 15),
        ('towards', 15),
        ('why', 15),
        ('together', 15),
        ('yourselves', 16),
        ('find', 16),
        ('before', 16),
        ('during', 16),
        ('whither', 16),
        ('for', 16),
        ('seemed', 16),
        ('put', 16),
        ('or', 16),
        ('alone', 16),
        ('anyhow', 16),
        ('sometime', 16),
        ('below', 16),
        ('toward', 16),
        ('cant', 16),
        ('two', 16),
        ('itself', 16),
        ('somewhere', 17),
        ('do', 17),
        ('hereafter', 17),
        ('ourselves', 17),
        ('whereupon', 17),
        ('could', 17),
        ('been', 17),
        ('another', 17),
('twenty', 17),
 ('whereafter', 17),
 ('inc', 17),
 ('may', 17),
 ('hereupon', 17),
 ('being', 18),
 ('still', 18),
 ('re', 18),
 ('to', 18),
 ('might', 18),
 ('get', 18),
 ('every', 18),
 ('front', 18),
 ('this', 18),
 ('often', 18),
 ('beyond', 18),
 ('nine', 18),
 ('thereupon', 18),
 ('last', 18),
 ('amount', 18),
 ('one', 18),
 ('throughout', 18),
 ('least', 18),
 ('much', 18),
 ('until', 18),
 ('himself', 18),
 ('mostly', 18),
 ('on', 18),
 ('too', 18),
 ('whether', 18),
 ('almost', 18),
 ('of', 18),
 ('ie', 18),
 ('other', 18),
 ('you', 18),
 ('without', 18),
 ('yours', 18),
 ('afterwards', 19),
 ('only', 19),
 ('herein', 19),
 ('first', 19),
 ('someone', 19),
 ('nor', 19),
 ('beforehand', 19),
 ('due', 19),
 ('besides', 19),
 ('what', 19),
 ('since', 19),
 ('between', 19),
 ('somehow', 19),
 ('nowhere', 19),
 ('fifteen', 19),
 ('anything', 19),
 ('hers', 19),
 ('own', 19),
 ('co', 19),
 ('seems', 19),
 ('such', 19),
 ('there', 19),
 ('next', 19),
 ('elsewhere', 19),
 ('amongst', 19),
 ('off', 19),
 ('those', 19),
 ('must', 19),
 ('while', 19),
 ('were', 19),
 ('thus', 19),
 ('have', 19),
 ('made', 19),
 ('is', 19),
 ('latter', 19),
 ('beside', 19),
 ('how', 19),
 ('several', 19),
 ('else', 19),
 ('give', 19),
 ('rather', 19),
 ('con', 19),
 ('once', 19),
 ('anyway', 20),
 ('four', 20),
 ('whole', 20),
 ('into', 20),
 ('around', 20),
 ('name', 20),
 ('cry', 20),
 ('ten', 20),
 ('back', 20),
 ('bottom', 20),
 ('please', 20),
 ('everything', 20),
 ('be', 20),
 ('we', 20),
 ('amoungst', 20),
 ('here', 20),
 ('found', 20),
 ('along', 20),
 ('about', 20),
 ('can', 20),
 ('done', 20),
 ('yourself', 20),
 ('i', 20),
 ('call', 20),
 ('part', 20),
 ('everywhere', 20),
 ('former', 20),
 ('than', 20),
 ('bill', 20),
 ('describe', 20),
 ('an', 20),
 ('further', 20),
 ('when', 20),
 ('that', 20),
 ('take', 20),
 ('becomes', 20),
 ('see', 20),
 ('anywhere', 20),
 ('nobody', 20),
 ('so', 20),
 ('serious', 20),
 ('eleven', 21),
 ('over', 21),
 ('de', 21),
 ('cannot', 21),
 ('always', 21),
 ('therein', 21),
 ('twelve', 21),
 ('eg', 21),
 ('some', 21),
 ('un', 21),
 ('ever', 21),
 ('full', 21),
 ('am', 21),
 ('after', 21),
 ('ltd', 21),
 ('hence', 21),
 ('formerly', 21),
 ('thereafter', 21),
 ('within', 21),
 ('everyone', 21),
 ('thick', 21),
 ('anyone', 21),
 ('whom', 21),
 ('interest', 21),
 ('was', 21),
 ('latterly', 21),
 ('mine', 21),
 ('any', 21),
 ('these', 21),
 ('hasnt', 21),
 ('in', 21),
 ('no', 21),
 ('whence', 21),
 ('wherein', 21),
 ('noone', 21),
 ('sometimes', 21),
 ('their', 21),
 ('five', 21),
 ('less', 22),
 ('move', 22),
 ('via', 22),
 ('mill', 22),
 ('whose', 22),
 ('ours', 22),
 ('thereby', 22),
 ('they', 22),
 ('each', 22),
 ('side', 22),
 ('namely', 22),
 ('forty', 22),
 ('above', 22),
 ('across', 22),
 ('by', 22),
 ('thence', 22),
 ('keep', 22),
 ('etc', 22),
 ('became', 22),
 ('otherwise', 22),
 ('whatever', 22),
 ('top', 22),
 ('system', 22),
 ('becoming', 22),
 ('will', 22),
 ('something', 22),
 ('six', 22),
 ('which', 22),
 ('eight', 22),
 ('your', 22),
 ('nevertheless', 22),
 ('except', 22),
 ('indeed', 23),
 ('go', 23),
 ('behind', 23),
 ('myself', 23),
 ('either', 23),
 ('because', 23),
 ('yet', 23),
 ('however', 23),
 ('her', 23),
 ('would', 23),
 ('few', 23),
 ('therefore', 23),
 ('thru', 23),
 ('more', 23),
 ('also', 23),
 ('none', 23),
 ('his', 23),
 ('most', 23),
 ('nothing', 23),
 ('its', 23),
 ('herself', 24),
 ('very', 24),
 ('our', 24),
 ('out', 24),
 ('per', 24),
 ('although', 24),
 ('sixty', 24),
 ('from', 24),
 ('thin', 24),
 ('themselves', 24),
 ('a', 24),
 ('me', 24),
 ('us', 24),
 ('whereas', 24),
 ('upon', 24),
 ('detail', 25),
 ('should', 25),
 ('under', 25),
 ('him', 25),
 ('neither', 25),
 ('couldnt', 25),
 ('moreover', 25),
 ('empty', 25),
 ('up', 25),
 ('whenever', 25),
 ('three', 25),
 ('at', 25),
 ('seem', 25),
 ('as', 25),
 ('she', 25),
 ('fill', 25),
 ('whereby', 25),
 ('meanwhile', 25),
 ('others', 25),
 ('not', 26),
 ('though', 26),
 ('become', 26),
 ('many', 26),
 ('onto', 26),
 ('hereby', 26),
 ('with', 26),
 ('sincere', 26),
 ('perhaps', 26),
 ('are', 27),
 ('never', 27),
 ('among', 27),
 ('whoever', 27),
 ('had', 28),
 ('and', 28),
 ('wherever', 28),
 ('my', 29),
 ('then', 29),
 ('again', 30),
 ('enough', 31),
 ('same', 33),
 ('he', 34)]

STOP_WORDS_OPTIMIZED =['all',
        'afterwards',
        'eleven',
        'less',
        'being',
        'indeed',
        'over',
        'move',
        'anyway',
        'detail',
        'four',
        'not',
        'via',
        'through',
        'yourselves',
        'go',
        'mill',
        'still',
        'find',
        'before',
        'whose',
        'but',
        're',
        'somewhere',
        'herself',
        'show',
        'had',
        'behind',
        'should',
        'to',
        'only',
        'whole',
        'under',
        'herein',
        'ours',
        'has',
        'might',
        'into',
        'first',
        'do',
        'them',
        'someone',
        'around',
        'thereby',
        'get',
        'very',
        'de',
        'myself',
        'cannot',
        'every',
        'they',
'front',
 'during',
 'now',
 'him',
 'nor',
 'hereafter',
 'well',
 'name',
 'always',
 'cry',
 'whither',
 'beforehand',
 'this',
 'either',
 'though',
 'each',
 'become',
 'if',
 'where',
 'side',
 'therein',
 'twelve',
 'because',
 'often',
 'ten',
 'due',
 'the',
 'eg',
 'some',
 'back',
 'fify',
 'namely',
 'besides',
 'are',
 'our',
 'beyond',
 'ourselves',
 'out',
 'even',
 'what',
 'for',
 'bottom',
 'since',
 'please',
 'forty',
 'per',
 'yet',
 'everything',
 'enough',
 'un',
 'above',
 'between',
 'nine',
 'neither',
 'seemed',
 'ever',
 'across',
 'thereupon',
 'somehow',
 'be',
 'we',
 'full',
 'amoungst',
 'never',
 'however',
 'here',
 'am',
 'couldnt',
 'whereupon',
 'nowhere',
 'although',
 'found',
 'sixty',
 'along',
 'fifteen',
 'by',
 'after',
 'both',
 'about',
 'last',
 'her',
 'anything',
 'many',
 'could',
 'thence',
 'put',
 'against',
 'keep',
 'etc',
 'amount',
 'became',
 'hers',
 'ltd',
 'hence',
 'onto',
 'or',
 'otherwise',
 'among',
 'own',
 'co',
 'seeming',
 'formerly',
 'can',
 'seems',
 'thereafter',
 'within',
 'whatever',
 'one',
 'down',
 'alone',
 'everyone',
 'done',
 'been',
 'another',
 'such',
 'whoever',
 'moreover',
 'thick',
 'throughout',
 'anyhow',
 'yourself',
 'he',
 'from',
 'i',
 'would',
 'few',
 'twenty',
 'top',
 'there',
 'system',
 'least',
 'next',
 'anyone',
 'whom',
 'thin',
 'much',
 'call',
 'therefore',
 'interest',
 'themselves',
 'thru',
 'was',
 'until',
 'empty',
 'more',
 'a',
 'himself',
 'elsewhere',
 'mostly',
 'on',
 'fire',
 'latterly',
 'becoming',
 'hereby',
 'amongst',
 'it',
 'part',
 'everywhere',
 'too',
 'former',
 'off',
 'with',
 'than',
 'those',
 'must',
 'me',
 'also',
 'none',
 'hundred',
 'whether',
 'bill',
 'up',
 'us',
 'will',
 'whenever',
 'while',
 'sometime',
 'below',
 'three',
 'were',
 'already',
 'toward',
 'my',
 'at',
 'and',
 'whereafter',
 'then',
 'almost',
 'of',
 'sincere',
 'describe',
 'thus',
 'mine',
 'an',
 'cant',
 'his',
 'something',
 'have',
 'further',
 'seem',
 'made',
 'ie',
 'any',
 'as',
 'she',
 'is',
 'these',
 'hasnt',
 'inc',
 'in',
 'no',
 'perhaps',
 'latter',
 'six',
 'when',
 'whence',
 'same',
 'wherein',
 'beside',
 'how',
 'that',
 'other',
 'take',
 'which',
 'becomes',
 'you',
 'several',
 'towards',
 'whereas',
 'see',
 'again',
 'may',
 'who',
 'upon',
 'anywhere',
 'most',
 'hereupon',
 'eight',
 'two',
 'nothing',
 'fill',
 'else',
 'why',
 'your',
 'give',
 'whereby',
 'third',
 'nevertheless',
 'nobody',
 'noone',
 'sometimes',
 'itself',
 'except',
 'together',
 'their',
 'rather',
 'without',
 'so',
 'wherever',
 'five',
 'serious',
 'meanwhile',
 'con',
 'its',
 'yours',
 'others',
 'once'] 
